repos:
- repo: local
  hooks:
  - id: qmllint
    name: qmllint
    entry: qmllint
    language: system
    files: \.qml$
  - id: flake8
    name: flake8
    language: system
    entry: flake8 ./py
    files: \.py
