== Project outline

YubiKey Manager is a Qt5 application written in QML that uses the plugin PyOtherSide to enable
the backend logic to be written in Python 3. The python library yubikey-manager is needed to
communicate with the YubiKey, and may be installed from pip or other package managers.
If a specific version (or branch or commit) is needed for development, point to that version
in requirements.txt

== Working with the code

=== Install dependencies

It's assumed a Python environment with pip is installed.

==== Windows
Install https://www.qt.io/download[Qt5]. Build and install the Qt5 plugin http://pyotherside.readthedocs.io/en/latest/#building-pyotherside[PyOtherSide].
Make sure the http://www.swig.org/[swig] executable is in your PATH. Add http://libusb.info/[libusb] and https://developers.yubico.com/yubikey-personalization/[ykpers] DLLs to
the root of the repository of ykman (after setting up the project).

==== macOS

    $ brew install python3 swig ykpers libusb qt
    # Allow access to qmake - see https://superuser.com/a/1153338/104372
    $ brew link qt --force

Build and install the Qt5 plugin http://pyotherside.readthedocs.io/en/latest/#building-pyotherside[PyOtherSide].

==== Linux (Debian-based distributions)

    $ sudo add-apt-repository -y ppa:yubico/stable
    $ sudo apt update
    $ sudo apt install python3-yubikey-manager qml-module-qt-labs-settings qml-module-qtquick-dialogs \
      qml-module-qtquick-controls qt5-default libqt5svg5-dev qtdeclarative5-dev qtbase5-dev 
      qml-module-io-thp-pyotherside

=== Setup the repository:

    $ git clone https://github.com/Yubico/yubikey-manager-qt.git
    $ cd yubikey-manager-qt

=== Compile the app:

    $ qmake && make

=== Run the app:

    $ ykman-gui

=== Code Style & Linting

This project uses http://flake8.pycqa.org/[Flake8] (for the python parts) and qmllint 
(for the QML parts) for code style with a http://pre-commit.com/[pre-commit] hook.

To use these:

    $ pip install pre-commit flake8
    $ pre-commit install

== Using vagrant for development

A Vagrantfile with a development environment based on Ubuntu 16.04 is included in the repository.
It comes with Xfce4 as a desktop environment. To start the vagrant environment:

    $ cd vagrant/development
    $ vagrant up

The default root login credentials are root:root. The repository can be found as a synced folder under `/vagrant`.
Modify the provision.sh script to set up a USB filter to capture the device with VirtualBox.


== Building from source

=== Windows

First of all, set up the environment as described in the
link:../vagrant/windows/README.md[Vagrant VM README].

To build the project, run in command prompt (skip the `git checkout` step to build the latest commit):

    > git clone --recurse-submodules https://github.com/Yubico/yubikey-manager-qt.git
    > cd yubikey-manager-qt
    > git checkout yubikey-manager-qt-<VERSION>
    > git show --show-signature
    > vagrant\windows\build.bat

The `build.bat` script will output the build version number near the beginning.
Use that as the `<VERSION>` in the next series of commands. If you missed it,
you can find it as the `APP_VERSION=` variable in the `DEFINES` in
`Makefile.Release`.

To build the installer, plug in the code signing YubiKey and run:

    $ cd yubikey-manager-qt
    $ vagrant\windows\release.bat <VERSION>


== Publishing to Ubuntu PPA

 1. Update version number and signoff in `debian/changelog`.
 2. Build and upload package.

For (2) you can use the Vagrant VM in `vagrant/ppa`. You'll need to set up the
VM to capture the YubiKey containing your signing key. If you use VirtualBox,
you can do this by uncommenting the USB filter included in the `Vagrantfile`.
Then:

    alice@work $ cd yubikey-manager-qt/vagrant/ppa
    alice@work $ vagrant up
    alice@work $ vagrant ssh
    ubuntu@ubuntu-xenial $ gpg --recv-keys ABCDEF78
    ubuntu@ubuntu-xenial $ gpg2 --recv-keys ABCDEF78
    ubuntu@ubuntu-xenial $ gpg2 --card-status
    ubuntu@ubuntu-xenial $ cd yubikey-manager-qt
    ubuntu@ubuntu-xenial $ python3 compute-version.py yubikey-manager-qt- > VERSION
    ubuntu@ubuntu-xenial $ ~/scripts/make-ppa -k ABCDEF78 -p gpg2
