== Releasing on macOS

    python resources/mac/build_macos.py
    codesign --deep --force --verify --verbose --sign 'Developer ID Application' YubiKey\ Manager.app --entitlements resources/mac/Entitlements.plist
    sudo pkgbuild --sign 'Developer ID Installer' --install-location /Applications --component YubiKey\ Manager.app/ yubikey-manager-VERSION-mac.pkg
    gpg --detach-sign dist/yubikey-manager-VERSION-mac.pkg
    
== Releasing on Windows

    qmake ykman-gui.pro -r -spec win32-msvc2015
    jom qmake_all
    windeployqtqt ykman-gui/release/ykman-gui.exe -qmldir=yubikey-manager-qt
    cp ykman-cli/ykman.exe /ykman-gui/release/    
    Extract python-3.5.2-embed-win32.zip in release directory
    Add ykman + pip dependencies to release directory
    Add msvcp140.dll to release directory
    Add ucrt .dlls to release directory (C:\Program Files (x86)\Windows Kits\10\Redist\ucrt)
    Add ykman .dlls to release directory
    signtool.exe sign /fd SHA256 /t http://timestamp.verisign.com/scripts/timstamp.dll ykman-gui.exe
    signtool.exe sign /fd SHA256 /t http://timestamp.verisign.com/scripts/timstamp.dll ykman.exe
    makensis -D"VERSION=$VERSION" resources/win-installer.nsi
    signtool.exe sign /fd SHA256 /t http://timestamp.verisign.com/scripts/timstamp.dll yubikey-manager-$VERSION-win.exe
    gpg --detach-sign dist/yubikey-manager-VERSION-win.exe
